### ISSUE TITLE
[Module 4] Need to link the CC licenses to their actual pages

### ISSUE THREAD

**Issue by davetaz** [theodi/ODI-eLearning#4]
https://creativecommons.org/publicdomain/zero/1.0/
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by davetaz** [comment]
Also make the take me to link a "Create your own creative commons license" https://creativecommons.org/choose/

**Comment by aaronpont** [comment]
Thanks Dave, I was not sure which URL would be best, which is why I just went with a default home page.  Nice idea about taking them to build your own licence.
Developers, please amend as above.  I have updated the format for the changes in the wire frame for module 4, page 5a.  Please change all text for that page, just in case!
Thanks,
aAron

**Comment by jasonbutler** [comment]
Accordion content amended - links also copied through to the resources page as per current practice.

**Comment by davetaz** [comment]
@jasonbutler any chance you can add the phrases "closes #x" where x is the issue number to your commit messages as this will close the issue and point to the code that closes it. Thanks!

**Comment by davetaz** [comment]
Fixed by cc6fb12694ed59e28d75606149ed6b4e805b8235
